#!/bin/bash

echo "=========================================="
echo "HƯỚNG DẪN UPLOAD LÊN GITHUB"
echo "=========================================="
echo ""
echo "Vì không có git trong container, bạn có 3 cách:"
echo ""
echo "CÁCH 1: Sử dụng Python script (Khuyến nghị)"
echo "-------------------------------------------"
echo "1. Tạo GitHub Personal Access Token tại:"
echo "   https://github.com/settings/tokens"
echo "   - Click 'Generate new token (classic)'"
echo "   - Chọn quyền: repo (full control)"
echo "   - Copy token"
echo ""
echo "2. Chạy lệnh:"
echo "   cd /mnt/extra-addons/github_upload"
echo "   python3 upload_via_api.py"
echo ""
echo "3. Nhập token khi được yêu cầu"
echo ""
echo "CÁCH 2: Exit container và chạy trên host"
echo "-------------------------------------------"
echo "1. Exit khỏi container: exit"
echo "2. Chạy lệnh:"
echo "   cd /path/to/extra-addons/github_upload"
echo "   git init"
echo "   git remote add origin https://github.com/danganh1009/TTDN-16-04-N9.git"
echo "   git add ."
echo "   git commit -m 'Upload modules'"
echo "   git push -u origin main --force"
echo ""
echo "CÁCH 3: Upload qua GitHub Web"
echo "-------------------------------------------"
echo "1. Truy cập: https://github.com/danganh1009/TTDN-16-04-N9"
echo "2. Click 'Add file' > 'Upload files'"
echo "3. Kéo thả các thư mục từ /mnt/extra-addons/github_upload"
echo ""
echo "=========================================="
echo "Các module đã sẵn sàng:"
echo "- nhan_su"
echo "- quan_ly_du_an"
echo "- quan_ly_cong_viec"
echo "- thong_bao"
echo "- chat_noi_bo"
echo "- ai_chatbot"
echo "=========================================="
